function wellTempTab = importWellTemp(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  C10308AQUIFRO214M = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  C10308AQUIFRO214M = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  C10308AQUIFRO214M = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  wellTempTab = importWellTemp("C:\Users\Asus\OneDrive\INRS\WellTProfiles\test\5C10308_aquifro2_14m.xlsx", "DAT", [2, 24285]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Sep-2020 07:01:04

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 200000];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["dateTime", "tempC"];
opts.SelectedVariableNames = ["dateTime", "tempC"];
opts.VariableTypes = ["datetime", "double"];
opts = setvaropts(opts, 1, "InputFormat", "");

% Import the data
wellTempTab = readtable(workbookFile, opts, "UseExcel", false);
% Keep only line with values. remove NaN
wellTempTab = wellTempTab(~isnan(wellTempTab.tempC), :);
for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    wellTempTab = [wellTempTab; tb]; %#ok<AGROW>
end

end